#!/usr/bin/env python3
"""
Generate src/fs/uft_amiga_virus_db.c from data/amiga_bootblock_viruses.tsv.

The TSV is the SSOT for Amiga bootblock/link/file virus catalog entries.
This generator emits a const C array so uft_amiga_get_virus_db() can
return the catalog without runtime I/O.

Rows with pattern_hex == "PENDING" emit placeholder entries with
pattern_len = 0 — the scanner must skip those for matching but may
still display the name in a UI catalog.

Usage:
  python3 scripts/generators/gen_virus_db.py         # generate in place
  python3 scripts/generators/gen_virus_db.py --check # verify stdout diffs
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import pathlib
import sys
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
TSV_PATH = ROOT / "data" / "amiga_bootblock_viruses.tsv"
OUT_PATH = ROOT / "src" / "fs" / "uft_amiga_virus_db.c"


@dataclass
class VirusRow:
    id: int
    name: str
    category: str
    pattern_hex: str
    pattern_mask_hex: str
    first_seen: str
    source: str
    disinfect_strategy: str


def load_tsv(path: pathlib.Path) -> list[VirusRow]:
    rows: list[VirusRow] = []
    seen_ids: set[int] = set()
    seen_names: set[str] = set()
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.reader(fh, delimiter="\t")
        header = None
        for raw in reader:
            if not raw or raw[0].startswith("#"):
                continue
            if header is None:
                header = raw
                continue
            if len(raw) < 8:
                raise ValueError(f"Row has {len(raw)} fields, expected 8: {raw}")
            row = VirusRow(
                id=int(raw[0]),
                name=raw[1].strip(),
                category=raw[2].strip(),
                pattern_hex=raw[3].strip(),
                pattern_mask_hex=raw[4].strip(),
                first_seen=raw[5].strip(),
                source=raw[6].strip(),
                disinfect_strategy=raw[7].strip(),
            )
            if row.id in seen_ids:
                raise ValueError(f"Duplicate id {row.id} ({row.name})")
            if row.name in seen_names:
                raise ValueError(f"Duplicate name {row.name!r}")
            if row.disinfect_strategy != "REPORT_ONLY":
                raise ValueError(
                    f"Row {row.id} ({row.name}): disinfect_strategy must be "
                    f"REPORT_ONLY, got {row.disinfect_strategy!r}. "
                    f"UFT does not auto-kill viruses."
                )
            if row.category not in {
                "bootvirus", "linkvirus", "filevirus", "bootblock", "trojan"
            }:
                raise ValueError(
                    f"Row {row.id}: unknown category {row.category!r}"
                )
            seen_ids.add(row.id)
            seen_names.add(row.name)
            rows.append(row)
    rows.sort(key=lambda r: r.id)
    return rows


def hex_to_bytes(h: str) -> bytes:
    if h == "PENDING":
        return b""
    if len(h) % 2 != 0:
        raise ValueError(f"Hex string length must be even: {h!r}")
    try:
        return bytes.fromhex(h)
    except ValueError as e:
        raise ValueError(f"Invalid hex: {h!r}") from e


def escape_c_string(s: str) -> str:
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif 0x20 <= ord(ch) < 0x7F:
            out.append(ch)
        else:
            out.append(f'\\x{ord(ch):02x}')
    return "".join(out)


def category_enum(cat: str) -> str:
    return {
        "bootvirus":  "UFT_AMIGA_VIRUS_CAT_BOOT",
        "linkvirus":  "UFT_AMIGA_VIRUS_CAT_LINK",
        "filevirus":  "UFT_AMIGA_VIRUS_CAT_FILE",
        "bootblock":  "UFT_AMIGA_VIRUS_CAT_BOOTBLOCK",
        "trojan":     "UFT_AMIGA_VIRUS_CAT_TROJAN",
    }[cat]


def generate_c(rows: list[VirusRow], tsv_path: pathlib.Path) -> str:
    tsv_bytes = tsv_path.read_bytes()
    tsv_hash = hashlib.sha256(tsv_bytes).hexdigest()[:16]

    lines: list[str] = []
    lines.append(f"""\
/*
 * uft_amiga_virus_db.c — Amiga bootblock/link/file virus catalog.
 *
 * AUTOGENERATED from data/amiga_bootblock_viruses.tsv.
 * Do NOT edit by hand — changes will be overwritten by
 * scripts/generators/gen_virus_db.py.
 *
 * TSV SHA-256 prefix: {tsv_hash}
 * Row count:          {len(rows)}
 *
 * Forensic rule: every row's disinfect_strategy is REPORT_ONLY.
 * UFT does not auto-kill viruses (see XCOPY_INTEGRATION_TODO § Anti-Features).
 */
#include "uft/uft_amiga_virus_db.h"

#include <stddef.h>
#include <stdint.h>
""")

    # Emit pattern + mask blobs as static arrays
    for row in rows:
        pat = hex_to_bytes(row.pattern_hex)
        msk = hex_to_bytes(row.pattern_mask_hex)
        if len(pat) != len(msk):
            raise ValueError(
                f"Row {row.id} ({row.name}): pattern ({len(pat)}B) and "
                f"mask ({len(msk)}B) length mismatch")
        if not pat:
            continue  # PENDING — no blob needed
        pat_bytes = ", ".join(f"0x{b:02X}" for b in pat)
        msk_bytes = ", ".join(f"0x{b:02X}" for b in msk)
        lines.append(
            f"static const uint8_t VIRUS_{row.id}_PAT[] = {{ {pat_bytes} }};")
        lines.append(
            f"static const uint8_t VIRUS_{row.id}_MSK[] = {{ {msk_bytes} }};")
        lines.append("")

    lines.append("static const uft_amiga_virus_sig_t VIRUS_DB[] = {")
    for row in rows:
        pat = hex_to_bytes(row.pattern_hex)
        pat_ref = f"VIRUS_{row.id}_PAT" if pat else "NULL"
        msk_ref = f"VIRUS_{row.id}_MSK" if pat else "NULL"
        lines.append("    {")
        lines.append(f"        .id = {row.id},")
        lines.append(f'        .name = "{escape_c_string(row.name)}",')
        lines.append(f"        .category = {category_enum(row.category)},")
        lines.append(f"        .pattern = {pat_ref},")
        lines.append(f"        .pattern_mask = {msk_ref},")
        lines.append(f"        .pattern_len = {len(pat)},")
        lines.append(f'        .first_seen = "{escape_c_string(row.first_seen)}",')
        lines.append(f'        .source = "{escape_c_string(row.source)}",')
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const size_t UFT_AMIGA_VIRUS_DB_COUNT = "
                 f"sizeof(VIRUS_DB) / sizeof(VIRUS_DB[0]);")
    lines.append("")
    lines.append("const uft_amiga_virus_sig_t *uft_amiga_get_virus_db(size_t *count)")
    lines.append("{")
    lines.append("    if (count) *count = UFT_AMIGA_VIRUS_DB_COUNT;")
    lines.append("    return VIRUS_DB;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Print generated output to stdout; do not write file.")
    args = ap.parse_args()

    rows = load_tsv(TSV_PATH)
    c_source = generate_c(rows, TSV_PATH)

    if args.check:
        sys.stdout.write(c_source)
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(c_source, encoding="utf-8")
    pending_count = sum(1 for r in rows if r.pattern_hex == "PENDING")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    print(f"  Rows:    {len(rows)}")
    print(f"  Pending: {pending_count} (no signature yet)")
    print(f"  Active:  {len(rows) - pending_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
