#include "uft/whdload/whdload_resload_api.h"

static const uft_whd_resload_api_t g_api[] = {
  {"resload_Abort","quit and return to operating system","This aborts and terminates the installed program and causes WHDLoad to",1},
  {"resload_Control","get/set various variables, control WHDLoad","control function of WHDLoad, allows to get and set various variables",0},
  {"resload_CRC16","calculate ANSI conform 16 bit CRC checksum","calculate ANSI conform 16 bit CRC checksum",0},
  {"resload_Decrunch","uncompress data in memory","This unpacks compressed data in memory. Known compressed data formats",0},
  {"resload_Delay","wait some time or for a user action","Waits the specified time or until any button/key is pressed. All",0},
  {"resload_DeleteFile","delete a file","This function deletes the file with the specified name.",0},
  {"resload_Delta","apply WDelta file","Applies the differences provided via the delta data onto the source",0},
  {"resload_DiskLoad","load part of a disk image","Loads a part from a disk image as specified by the parameters.",1},
  {"resload_DiskLoadDev","load part from a floppy disk","Loads a given amount of data from a floppy device.",1},
  {"resload_Examine","get information about a file or directory","Fills the supplied FileInfoBlock with information about the",0},
  {"resload_ExNext","get information about next directory entry","Fills the supplied FileInfoBlock with information about the next",0},
  {"resload_FlushCache","flush and clear the CPU caches","clears all CPU caches",0},
  {"resload_GetCustom","get Custom argument","Get the string which has been specified via the Custom/S option.",0},
  {"resload_GetFileSize","get the size of a file","Gets the size of a file (checks if a file exists).",0},
  {"resload_GetFileSizeDec","get the size of a packed file","Gets the uncompressed size of a packed file (checks if a file exists).",0},
  {"resload_ListFiles","list file names in a directory","Writes the names of all files in the specified directory to the",0},
  {"resload_LoadFile","load a file into memory","Loads the file to the specified memory address.",0},
  {"resload_LoadFileDecrunch","load a file and uncompress it","Loads the specified file into memory and unpack it if compressed using",0},
  {"resload_LoadFileOffset","loads a part of a file into memory","Loads a part of a file into memory. The part of the file is specified",0},
  {"resload_LoadKick","load Kickstart image","Loads the Kickstart image with the specified name into ExpMem.",0},
  {"resload_Log","put custom message into log file","This function puts a formatted message into the WHDLoad log file",0},
  {"resload_Patch","apply patch list","Modifies memory using commands from the specified patch list.",0},
  {"resload_PatchSeg","apply patch list to a segment list","This function is similar to resload_Patch. But instead of patching a",0},
  {"resload_ProtectRead","mark memory as read protected","Protects the specified memory against reading by the processor.",0},
  {"resload_ProtectReadWrite","mark memory as read and write protected","Protects the specified memory against reading and writing by the",0},
  {"resload_ProtectRemove","remove protection from memory area","Remove a previously set protection.",0},
  {"resload_ProtectSMC","detect self modifying code","Enables automatic detection of self modifying code (SMC) in the",0},
  {"resload_ProtectWrite","mark memory as write protected","Protects the selected area against writing by the processor.",0},
  {"resload_ReadJoyPort","return the state of the selected joy/mouse port","This function returns the type and the current position/button state of",0},
  {"resload_Relocate","relocate an AmigaDOS executable","Relocates a standard AmigaDOS executable in memory. By default the",0},
  {"resload_SaveFile","write memory to a file","Writes specified memory area to a file using the specified file name.",0},
  {"resload_SaveFileOffset","write memory to a file at given offset","Writes specified memory area to a file at specified offset using the",0},
  {"resload_SetCACR","set cacheability for BaseMem","This function enables/disables the CPU caches.",0},
  {"resload_SetCPU","control CPU setup","This function changes the cacheability of memory areas and changes the",0},
  {"resload_VSNPrintF","format data into a character stream","This function performs a exec.RawDoFmt/C.sprintf-like formatting of",1},
};

const uft_whd_resload_api_t *uft_whd_resload_api_list(size_t *out_count){ if(out_count)*out_count=sizeof(g_api)/sizeof(g_api[0]); return g_api; }
