/* SPDX-License-Identifier: GPL-2.0-or-later */
/**
 * @file test_fm_echte_aufnahme.c
 * @brief Der FM-Dekoder gegen eine ECHTE Aufnahme von 1979 (MF-869)
 *
 * ── Was MF-864 offenlassen musste ────────────────────────────────────
 *
 * MF-864 hat den FM-Sektordekoder gebaut — vorher bestand er aus zwei
 * Kommentaren („FM sector decoding would go here"). Belegt war er gegen
 * eine ERZEUGTE Pruefspur, und der Commit sagte das ausdruecklich:
 *
 *     „Was das nicht belegt: das Verhalten an einer echten Aufnahme.
 *      Im Korpus liegt kein FM-Flussabzug (P3-123c)."
 *
 * Seit der Korpus-Beschaffung (MF-866, Eigentuemer-Entscheidung
 * 2026-09-04) liegt einer darin, und seit MF-868 ist der A2R-Leser in
 * der Lage, ihn zu oeffnen. Dieser Test loest den Vorbehalt ein.
 *
 * ── Die Messkette ────────────────────────────────────────────────────
 *
 *   1. A2R oeffnen. Die Aufloesung kommt aus der DATEI
 *      (62 500 ps je Tick), nicht aus einer Konstante.
 *   2. Zellenzeit aus dem Intervall-HISTOGRAMM bestimmen, nicht
 *      annehmen. Die IMD nennt „FM 500 kbps"; ob das die Daten- oder
 *      die Kanalrate meint, ist genau die Sorte Annahme, die in diesem
 *      Baum dreimal schiefging. Gemessen: zwei Berge bei rund 2000 und
 *      4000 ns — das klassische FM-Muster, Zelle ~2125 ns.
 *   3. Durch `flux_decode_track()` mit `FLUX_ENC_FM`.
 *   4. Die 26 Sektoren byteweise gegen die IMD DESSELBEN Objekts.
 *
 * ── Warum die IMD eine fremde Hand ist ───────────────────────────────
 *
 * Ihre Kopfzeile lautet „Generated by Applesauce Fast Imager 1.88.4".
 * Applesauce hat dieselbe Diskette mit dem EIGENEN Dekoder gelesen; UFT
 * dekodiert den Fluss. Zwei Umsetzungen, dieselbe Diskette.
 *
 * Dazu kommen die CRCs: sie stehen auf der Diskette selbst, 1979
 * geschrieben. Ein Dekoder, der falsch liest, bekommt sie nicht alle
 * gruen.
 *
 * ── Gemessenes Ergebnis (2026-09-04) ─────────────────────────────────
 *
 *   Aufnahme     Typ 1 (timing), 77 250 Byte, 208 000 us, 288,5 U/min
 *   Dekodiert    32 Sektoren, ID-CRC falsch 0, Daten-CRC falsch 0
 *   Kopffelder   C=0 H=0 S=1..26 N=0 (128 Byte)
 *   Vergleich    26 von 26 byteidentisch zur IMD
 *
 * ── Warum dieser Test sich selbst ueberspringt ───────────────────────
 *
 * `tests/corpus/` ist ungetrackt: an keinem der archive.org-Objekte
 * steht ein Rechte-Feld (ueber die Metadaten-API gemessen), die Lage
 * ist ungeklaert, Zone PRUEFEN. Wer den Korpus nicht hat, bekommt einen
 * BENANNTEN Skip — keinen gruenen Lauf, der Sicherheit vortaeuscht, und
 * keinen roten, der eine fehlende Datei als Fehler ausgibt.
 *
 * Beschaffung und Pruefsummen: `tests/corpus_manifest/manifest.json`,
 * Eintrag KOR-a.
 */
#include "uft/parsers/uft_a2r_parser.h"
#include "uft/flux/uft_flux_decoder.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ctest wertet 77 als „uebersprungen" (SKIP_RETURN_CODE). */
#define SKIP_CODE 77

/* Der Pfad kommt aus dem Bausystem, nicht aus einem geratenen relativen
 * Pfad: `UFT_CORPUS_RESTRICTED_DIR` ist die Konvention dieses Baums fuer
 * den rechtlich ungeklaerten Teil des Korpus. */
#ifndef UFT_CORPUS_RESTRICTED_DIR
#define UFT_CORPUS_RESTRICTED_DIR "tests/corpus"
#endif
#define KOR_A UFT_CORPUS_RESTRICTED_DIR "/kor_a/"     "CPM Ver 2.2 CBIOS Rev 3.1 Disk Jockey 2D @ E000h (1979)"

static const char *A2R_PFAD = KOR_A ".a2r";
static const char *IMD_PFAD = KOR_A ".imd";

#define SEKTOREN   26
#define GROESSE   128

static int _fail = 0;
#define PRUEFE(c, m) do { if (!(c)) { \
    printf("  FEHLER: %s  (%s:%d)\n", (m), __FILE__, __LINE__); _fail++; } \
    } while (0)

/* ── IMD: Spur 0 herausholen ──────────────────────────────────────── */
static int imd_spur0(const char *pfad, uint8_t out[SEKTOREN][GROESSE])
{
    FILE *f = fopen(pfad, "rb");
    if (!f) return -1;
    static uint8_t b[1u << 20];
    size_t n = fread(b, 1, sizeof b, f);
    fclose(f);
    if (n < 64) return -1;

    size_t i = 0;
    while (i < n && b[i] != 0x1A) i++;
    if (i >= n) return -1;
    i++;                                        /* hinter das 0x1A */

    if (i + 5 > n) return -1;
    uint8_t n_sek = b[i + 3], gcode = b[i + 4], kopf = b[i + 2];
    i += 5;
    if (gcode != 0 || n_sek != SEKTOREN) return -2;   /* 128 B, 26 Sekt */

    uint8_t nummern[256];
    if (i + n_sek > n) return -1;
    memcpy(nummern, &b[i], n_sek); i += n_sek;
    if (kopf & 0x80) i += n_sek;
    if (kopf & 0x40) i += n_sek;

    int gefunden = 0;
    for (uint8_t k = 0; k < n_sek; k++) {
        if (i >= n) return -1;
        uint8_t typ = b[i++];
        uint8_t s = nummern[k];
        if (typ == 0) continue;
        if (typ == 1 || typ == 3 || typ == 5 || typ == 7) {
            if (i + GROESSE > n) return -1;
            if (s >= 1 && s <= SEKTOREN) {
                memcpy(out[s - 1], &b[i], GROESSE);
                gefunden++;
            }
            i += GROESSE;
        } else {
            if (i >= n) return -1;
            if (s >= 1 && s <= SEKTOREN) {
                memset(out[s - 1], b[i], GROESSE);
                gefunden++;
            }
            i++;
        }
    }
    return gefunden;
}

/* ── A2R-Flussbytes -> Intervalle in Ticks ────────────────────────── */
static size_t intervalle(const uint8_t *d, uint32_t n,
                         uint32_t *out, size_t max)
{
    size_t k = 0;
    uint32_t traeger = 0;
    for (uint32_t i = 0; i < n && k < max; i++) {
        if (d[i] == 0xFF) { traeger += 0xFF; continue; }
        out[k++] = traeger + d[i];
        traeger = 0;
    }
    return k;
}

/** Kleinster deutlicher Berg im Intervall-Histogramm = Zellenzeit. */
static double zellenzeit_messen(const uint32_t *iv, size_t n, double ns_tick)
{
    enum { BINS = 60, BIN_NS = 250 };
    uint32_t hist[BINS];
    memset(hist, 0, sizeof hist);
    for (size_t i = 0; i < n; i++) {
        int b = (int)((iv[i] * ns_tick) / BIN_NS);
        if (b >= 0 && b < BINS) hist[b]++;
    }
    uint32_t schwelle = (uint32_t)(n / 50);
    for (int b = 1; b < BINS - 1; b++) {
        if (hist[b] >= schwelle &&
            hist[b] >= hist[b - 1] && hist[b] >= hist[b + 1])
            return (b + 0.5) * BIN_NS;
    }
    return 0.0;
}

int main(void)
{
    setvbuf(stdout, NULL, _IONBF, 0);
    printf("=== FM gegen eine echte Aufnahme von 1979 (MF-869) ===\n");

    FILE *pr = fopen(A2R_PFAD, "rb");
    if (!pr) {
        printf("  UEBERSPRUNGEN: %s fehlt.\n", A2R_PFAD);
        printf("  Der Korpus ist ungetrackt (Rechtslage ungeklaert, Zone\n");
        printf("  PRUEFEN). Beschaffung: tests/corpus_manifest/manifest.json,\n");
        printf("  Eintrag KOR-a.\n");
        return SKIP_CODE;
    }
    fclose(pr);

    /* ── Die fremde Hand zuerst ───────────────────────────────────── */
    static uint8_t imd[SEKTOREN][GROESSE];
    int n_imd = imd_spur0(IMD_PFAD, imd);
    if (n_imd < 0) {
        printf("  UEBERSPRUNGEN: IMD-Referenz nicht lesbar (%d).\n", n_imd);
        return SKIP_CODE;
    }
    printf("  IMD (Applesauce Fast Imager 1.88.4): %d Sektoren\n", n_imd);
    PRUEFE(n_imd == SEKTOREN, "IMD-Spur 0 hat nicht 26 Sektoren");

    /* ── UFT: A2R -> Fluss -> FM ──────────────────────────────────── */
    a2r_context_t *ctx = a2r_open(A2R_PFAD);
    PRUEFE(ctx != NULL, "a2r_open fehlgeschlagen");
    if (!ctx) return 1;

    double ns_tick = ctx->resolution_ps ? ctx->resolution_ps / 1000.0
                                        : (double)A2R_TICK_NS;
    printf("  Aufloesung aus der Datei: %u ps je Tick (%.1f ns)\n",
           ctx->resolution_ps, ns_tick);
    PRUEFE(ctx->resolution_ps > 0,
           "die Aufloesung kam nicht aus der Datei");

    a2r_track_t tr;
    memset(&tr, 0, sizeof tr);
    PRUEFE(a2r_read_track(ctx, 0, 0, &tr) == A2R_OK, "Location 0 nicht lesbar");

    const a2r_capture_t *cap = NULL;
    for (uint8_t c = 0; c < tr.capture_count; c++)
        if (tr.captures[c].capture_type == 1) { cap = &tr.captures[c]; break; }
    PRUEFE(cap != NULL, "keine Timing-Aufnahme auf Location 0");
    if (!cap) { a2r_free_track(&tr); a2r_close(ctx); return 1; }

    uint32_t *iv = (uint32_t *)malloc(sizeof(uint32_t) * cap->data_length);
    uint32_t *ab = (uint32_t *)malloc(sizeof(uint32_t) * cap->data_length);
    PRUEFE(iv && ab, "kein Speicher");
    if (!iv || !ab) { free(iv); free(ab); a2r_free_track(&tr);
                      a2r_close(ctx); return 1; }

    size_t n = intervalle(cap->data, cap->data_length, iv, cap->data_length);
    printf("  Aufnahme: %u Byte, %zu Flusswechsel, %.0f us\n",
           cap->data_length, n, cap->duration_us);

    double zelle = zellenzeit_messen(iv, n, ns_tick);
    printf("  Zellenzeit aus dem Histogramm: %.0f ns\n", zelle);
    /* FM auf 8 Zoll: rund 2 us je Kanalzelle. Die Schranke ist weit
     * gesetzt — geprueft wird, dass ueberhaupt GEMESSEN wurde, nicht
     * eine Wunschzahl. */
    PRUEFE(zelle > 1500.0 && zelle < 2800.0,
           "die gemessene Zellenzeit liegt ausserhalb des FM-Bereichs");

    uint64_t t = 0;
    for (size_t i = 0; i < n; i++) { t += iv[i]; ab[i] = (uint32_t)t; }

    flux_raw_data_t flux;
    memset(&flux, 0, sizeof flux);
    flux.transitions      = ab;
    flux.transition_count = (uint32_t)n;
    flux.sample_rate      = (uint32_t)(1e9 / ns_tick);

    flux_decoder_options_t opts;
    flux_decoder_options_init(&opts);
    opts.encoding   = FLUX_ENC_FM;
    opts.bitcell_ns = zelle;

    flux_decoded_track_t track;
    memset(&track, 0, sizeof track);
    flux_decode_track(&flux, &track, &opts);

    printf("  dekodiert: %u Sektoren, ID-CRC falsch %u, Daten-CRC falsch %u\n",
           (unsigned)track.sector_count,
           (unsigned)track.bad_id_crc, (unsigned)track.bad_data_crc);

    /* Die CRCs stehen auf der Diskette, 1979 geschrieben. Ein Dekoder,
     * der falsch liest, bekommt sie nicht alle gruen. */
    PRUEFE(track.sector_count >= SEKTOREN, "weniger als 26 Sektoren");
    PRUEFE(track.bad_id_crc == 0, "mindestens eine ID-Pruefsumme falsch");
    PRUEFE(track.bad_data_crc == 0, "mindestens eine Daten-Pruefsumme falsch");

    /* ── Der Vergleich ────────────────────────────────────────────── */
    uint8_t uft[SEKTOREN][GROESSE];
    int da[SEKTOREN + 1];
    memset(uft, 0, sizeof uft);
    memset(da, 0, sizeof da);
    for (size_t i = 0; i < track.sector_count; i++) {
        const flux_decoded_sector_t *s = &track.sectors[i];
        if (s->sector < 1 || s->sector > SEKTOREN) continue;
        if (da[s->sector] || !s->data || s->data_size != GROESSE) continue;
        memcpy(uft[s->sector - 1], s->data, GROESSE);
        da[s->sector] = 1;
    }

    int gleich = 0;
    for (int s = 1; s <= SEKTOREN; s++) {
        if (!da[s]) {
            printf("  Sektor %2d: von UFT nicht gelesen\n", s);
            continue;
        }
        if (memcmp(uft[s - 1], imd[s - 1], GROESSE) == 0) {
            gleich++;
        } else {
            int erste = 0;
            while (erste < GROESSE && uft[s-1][erste] == imd[s-1][erste])
                erste++;
            printf("  Sektor %2d: erste Abweichung bei Byte %d "
                   "(IMD %02X, UFT %02X)\n",
                   s, erste, imd[s-1][erste], uft[s-1][erste]);
        }
    }

    printf("\n  byteidentisch zur IMD: %d von %d\n", gleich, SEKTOREN);
    PRUEFE(gleich == SEKTOREN,
           "nicht alle 26 Sektoren stimmen mit Applesauces Dekoder ueberein");

    flux_decoded_track_free(&track);
    free(iv); free(ab);
    a2r_free_track(&tr);
    a2r_close(ctx);

    if (_fail) {
        printf("\nErgebnis: %d Pruefung(en) fehlgeschlagen\n", _fail);
        return 1;
    }
    printf("\nErgebnis: bestanden. Der FM-Dekoder liest eine echte "
           "Aufnahme so\nwie Applesauces eigener Dekoder.\n");
    return 0;
}
