name: Feature Request
description: Suggest a new feature for UnifiedFloppyTool
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true
  
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      placeholder: How would you use this feature?
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Format Support
        - Hardware Support
        - UI/UX Improvement
        - Performance
        - Documentation
        - Other
