#ifndef UFT_LOADERS_KRYOFLUXSTREAM_LOADER_KRYOFLUXSTREAM_H
#define UFT_LOADERS_KRYOFLUXSTREAM_LOADER_KRYOFLUXSTREAM_H


LIBFLUX_TRKSTREAM* DecodeKFStreamFile(LIBFLUX_CTX* flux_ctx,LIBFLUX_FXSA * fxs,char * file);

#endif /* UFT_LOADERS_KRYOFLUXSTREAM_LOADER_KRYOFLUXSTREAM_H */
