/* =====================================================================
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Source of truth: data/errors.tsv
 * Regenerate with: make generate  (or scripts/verify_errors_ssot.sh)
 * Any manual edits will be overwritten on the next generator run.
 * ===================================================================== */
#ifndef UFT_ERROR_COMPAT_GEN_H
#define UFT_ERROR_COMPAT_GEN_H

/**
 * @file uft_error_compat_gen.h
 * @brief Legacy error-alias compatibility (GENERATED).
 *
 * Generated from data/errors.tsv + data/errors_legacy_aliases.tsv by
 * scripts/generators/gen_errors_compat.py. Do not edit by hand.
 *
 * Provides every alias spelling catalogued in the four pre-SSOT
 * compat sources:
 *   - UFT_ERROR_<NAME>   (mixed-case, ~1127 uses in 107 files)
 *   - UFT_E_<NAME>       (short-form P2-ARCH-006 spelling)
 *   - UFT_ERR_NOMEM / UFT_ERR_UNSUPPORTED / ... (legacy short names)
 *   - UFT_E<short>       (posix-ish EINVAL, EIO, ...)
 *   - UFT_IR_ERR_* / UFT_DEC_ERR_* / UFT_IO_ERR_* (subsystem families)
 *
 * Every alias is `#define`d only if not already present, so this header
 * can coexist with the pre-SSOT compat headers during the cutover
 * without triggering redefinition warnings.
 *
 * To flag legacy usage in builds, define UFT_WARN_LEGACY_ERROR_ALIASES
 * at compile time. This is OFF by default (transition phase).
 */

#include "uft/uft_error.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------------ */
/* 1. UFT_ERROR_<NAME> — mixed-case canonical alias (auto-emitted from TSV) */
/* ------------------------------------------------------------------------ */
#ifndef UFT_ERROR_SUCCESS
#define UFT_ERROR_SUCCESS UFT_SUCCESS
#endif
#ifndef UFT_ERROR_INVALID_ARG
#define UFT_ERROR_INVALID_ARG UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERROR_BUFFER_TOO_SMALL
#define UFT_ERROR_BUFFER_TOO_SMALL UFT_ERR_BUFFER_TOO_SMALL
#endif
#ifndef UFT_ERROR_INVALID_PATH
#define UFT_ERROR_INVALID_PATH UFT_ERR_INVALID_PATH
#endif
#ifndef UFT_ERROR_NULL_POINTER
#define UFT_ERROR_NULL_POINTER UFT_ERR_NULL_POINTER
#endif
#ifndef UFT_ERROR_IO
#define UFT_ERROR_IO UFT_ERR_IO
#endif
#ifndef UFT_ERROR_FILE_NOT_FOUND
#define UFT_ERROR_FILE_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_ERROR_PERMISSION
#define UFT_ERROR_PERMISSION UFT_ERR_PERMISSION
#endif
#ifndef UFT_ERROR_FILE_EXISTS
#define UFT_ERROR_FILE_EXISTS UFT_ERR_FILE_EXISTS
#endif
#ifndef UFT_ERROR_EOF
#define UFT_ERROR_EOF UFT_ERR_EOF
#endif
#ifndef UFT_ERROR_FORMAT
#define UFT_ERROR_FORMAT UFT_ERR_FORMAT
#endif
#ifndef UFT_ERROR_FORMAT_DETECT
#define UFT_ERROR_FORMAT_DETECT UFT_ERR_FORMAT_DETECT
#endif
#ifndef UFT_ERROR_FORMAT_VARIANT
#define UFT_ERROR_FORMAT_VARIANT UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERROR_CORRUPTED
#define UFT_ERROR_CORRUPTED UFT_ERR_CORRUPTED
#endif
#ifndef UFT_ERROR_CRC
#define UFT_ERROR_CRC UFT_ERR_CRC
#endif
#ifndef UFT_ERROR_MEMORY
#define UFT_ERROR_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_ERROR_RESOURCE
#define UFT_ERROR_RESOURCE UFT_ERR_RESOURCE
#endif
#ifndef UFT_ERROR_BUSY
#define UFT_ERROR_BUSY UFT_ERR_BUSY
#endif
#ifndef UFT_ERROR_NOT_SUPPORTED
#define UFT_ERROR_NOT_SUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_ERROR_NOT_IMPLEMENTED
#define UFT_ERROR_NOT_IMPLEMENTED UFT_ERR_NOT_IMPLEMENTED
#endif
#ifndef UFT_ERROR_NOT_PERMITTED
#define UFT_ERROR_NOT_PERMITTED UFT_ERR_NOT_PERMITTED
#endif
#ifndef UFT_ERROR_HARDWARE
#define UFT_ERROR_HARDWARE UFT_ERR_HARDWARE
#endif
#ifndef UFT_ERROR_USB
#define UFT_ERROR_USB UFT_ERR_USB
#endif
#ifndef UFT_ERROR_DEVICE_NOT_FOUND
#define UFT_ERROR_DEVICE_NOT_FOUND UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_ERROR_TIMEOUT
#define UFT_ERROR_TIMEOUT UFT_ERR_TIMEOUT
#endif
#ifndef UFT_ERROR_INTERNAL
#define UFT_ERROR_INTERNAL UFT_ERR_INTERNAL
#endif
#ifndef UFT_ERROR_ASSERTION
#define UFT_ERROR_ASSERTION UFT_ERR_ASSERTION
#endif
#ifndef UFT_ERROR_UNKNOWN
#define UFT_ERROR_UNKNOWN UFT_ERR_UNKNOWN
#endif
#ifndef UFT_ERROR_FORMAT_INVALID
#define UFT_ERROR_FORMAT_INVALID UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERROR_UNKNOWN_FORMAT
#define UFT_ERROR_UNKNOWN_FORMAT UFT_ERR_UNKNOWN_FORMAT
#endif
#ifndef UFT_ERROR_ENCODING
#define UFT_ERROR_ENCODING UFT_ERR_ENCODING
#endif
#ifndef UFT_ERROR_LONG_TRACK
#define UFT_ERROR_LONG_TRACK UFT_ERR_LONG_TRACK
#endif
#ifndef UFT_ERROR_NON_STANDARD
#define UFT_ERROR_NON_STANDARD UFT_ERR_NON_STANDARD
#endif
#ifndef UFT_ERROR_SYNC_LOST
#define UFT_ERROR_SYNC_LOST UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_ERROR_WEAK_BITS
#define UFT_ERROR_WEAK_BITS UFT_ERR_WEAK_BITS
#endif
#ifndef UFT_ERROR_TIMING
#define UFT_ERROR_TIMING UFT_ERR_TIMING
#endif
#ifndef UFT_ERROR_ID_MISMATCH
#define UFT_ERROR_ID_MISMATCH UFT_ERR_ID_MISMATCH
#endif
#ifndef UFT_ERROR_DELETED_DATA
#define UFT_ERROR_DELETED_DATA UFT_ERR_DELETED_DATA
#endif
#ifndef UFT_ERROR_MISSING_SECTOR
#define UFT_ERROR_MISSING_SECTOR UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_ERROR_INCOMPLETE
#define UFT_ERROR_INCOMPLETE UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_ERROR_PLL_UNLOCK
#define UFT_ERROR_PLL_UNLOCK UFT_ERR_PLL_UNLOCK
#endif
#ifndef UFT_ERROR_PROTECTION
#define UFT_ERROR_PROTECTION UFT_ERR_PROTECTION
#endif
#ifndef UFT_ERROR_COPY_DENIED
#define UFT_ERROR_COPY_DENIED UFT_ERR_COPY_DENIED
#endif
#ifndef UFT_ERROR_WRITE_PROTECT
#define UFT_ERROR_WRITE_PROTECT UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_ERROR_WRITE_FAULT
#define UFT_ERROR_WRITE_FAULT UFT_ERR_WRITE_FAULT
#endif
#ifndef UFT_ERROR_TRACK_OVERFLOW
#define UFT_ERROR_TRACK_OVERFLOW UFT_ERR_TRACK_OVERFLOW
#endif
#ifndef UFT_ERROR_VERIFY_FAIL
#define UFT_ERROR_VERIFY_FAIL UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_ERROR_FILE_OPEN
#define UFT_ERROR_FILE_OPEN UFT_ERR_FILE_OPEN
#endif
#ifndef UFT_ERROR_FILE_READ
#define UFT_ERROR_FILE_READ UFT_ERR_FILE_READ
#endif
#ifndef UFT_ERROR_FILE_CREATE
#define UFT_ERROR_FILE_CREATE UFT_ERR_FILE_CREATE
#endif
#ifndef UFT_ERROR_FILE_SEEK
#define UFT_ERROR_FILE_SEEK UFT_ERR_FILE_SEEK
#endif
#ifndef UFT_ERROR_FILE_WRITE
#define UFT_ERROR_FILE_WRITE UFT_ERR_FILE_WRITE
#endif
#ifndef UFT_ERROR_CANCELLED
#define UFT_ERROR_CANCELLED UFT_ERR_CANCELLED
#endif
#ifndef UFT_ERROR_INVALID_STATE
#define UFT_ERROR_INVALID_STATE UFT_ERR_INVALID_STATE
#endif
#ifndef UFT_ERROR_VERSION
#define UFT_ERROR_VERSION UFT_ERR_VERSION
#endif
#ifndef UFT_ERROR_PLUGIN_LOAD
#define UFT_ERROR_PLUGIN_LOAD UFT_ERR_PLUGIN_LOAD
#endif
#ifndef UFT_ERROR_PLUGIN_NOT_FOUND
#define UFT_ERROR_PLUGIN_NOT_FOUND UFT_ERR_PLUGIN_NOT_FOUND
#endif

/* ------------------------------------------------------------------------ */
/* 2. UFT_E_<NAME> — short-form (auto-emitted from canonical TSV)           */
/* ------------------------------------------------------------------------ */
#ifndef UFT_E_INVALID_ARG
#define UFT_E_INVALID_ARG UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_BUFFER_TOO_SMALL
#define UFT_E_BUFFER_TOO_SMALL UFT_ERR_BUFFER_TOO_SMALL
#endif
#ifndef UFT_E_INVALID_PATH
#define UFT_E_INVALID_PATH UFT_ERR_INVALID_PATH
#endif
#ifndef UFT_E_NULL_POINTER
#define UFT_E_NULL_POINTER UFT_ERR_NULL_POINTER
#endif
#ifndef UFT_E_IO
#define UFT_E_IO UFT_ERR_IO
#endif
#ifndef UFT_E_FILE_NOT_FOUND
#define UFT_E_FILE_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_E_PERMISSION
#define UFT_E_PERMISSION UFT_ERR_PERMISSION
#endif
#ifndef UFT_E_FILE_EXISTS
#define UFT_E_FILE_EXISTS UFT_ERR_FILE_EXISTS
#endif
#ifndef UFT_E_EOF
#define UFT_E_EOF UFT_ERR_EOF
#endif
#ifndef UFT_E_FORMAT
#define UFT_E_FORMAT UFT_ERR_FORMAT
#endif
#ifndef UFT_E_FORMAT_DETECT
#define UFT_E_FORMAT_DETECT UFT_ERR_FORMAT_DETECT
#endif
#ifndef UFT_E_FORMAT_VARIANT
#define UFT_E_FORMAT_VARIANT UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_E_CORRUPTED
#define UFT_E_CORRUPTED UFT_ERR_CORRUPTED
#endif
#ifndef UFT_E_CRC
#define UFT_E_CRC UFT_ERR_CRC
#endif
#ifndef UFT_E_MEMORY
#define UFT_E_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_E_RESOURCE
#define UFT_E_RESOURCE UFT_ERR_RESOURCE
#endif
#ifndef UFT_E_BUSY
#define UFT_E_BUSY UFT_ERR_BUSY
#endif
#ifndef UFT_E_NOT_SUPPORTED
#define UFT_E_NOT_SUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_E_NOT_IMPLEMENTED
#define UFT_E_NOT_IMPLEMENTED UFT_ERR_NOT_IMPLEMENTED
#endif
#ifndef UFT_E_NOT_PERMITTED
#define UFT_E_NOT_PERMITTED UFT_ERR_NOT_PERMITTED
#endif
#ifndef UFT_E_HARDWARE
#define UFT_E_HARDWARE UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_USB
#define UFT_E_USB UFT_ERR_USB
#endif
#ifndef UFT_E_DEVICE_NOT_FOUND
#define UFT_E_DEVICE_NOT_FOUND UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_E_TIMEOUT
#define UFT_E_TIMEOUT UFT_ERR_TIMEOUT
#endif
#ifndef UFT_E_INTERNAL
#define UFT_E_INTERNAL UFT_ERR_INTERNAL
#endif
#ifndef UFT_E_ASSERTION
#define UFT_E_ASSERTION UFT_ERR_ASSERTION
#endif
#ifndef UFT_E_UNKNOWN
#define UFT_E_UNKNOWN UFT_ERR_UNKNOWN
#endif
#ifndef UFT_E_FORMAT_INVALID
#define UFT_E_FORMAT_INVALID UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_E_UNKNOWN_FORMAT
#define UFT_E_UNKNOWN_FORMAT UFT_ERR_UNKNOWN_FORMAT
#endif
#ifndef UFT_E_ENCODING
#define UFT_E_ENCODING UFT_ERR_ENCODING
#endif
#ifndef UFT_E_LONG_TRACK
#define UFT_E_LONG_TRACK UFT_ERR_LONG_TRACK
#endif
#ifndef UFT_E_NON_STANDARD
#define UFT_E_NON_STANDARD UFT_ERR_NON_STANDARD
#endif
#ifndef UFT_E_SYNC_LOST
#define UFT_E_SYNC_LOST UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_E_WEAK_BITS
#define UFT_E_WEAK_BITS UFT_ERR_WEAK_BITS
#endif
#ifndef UFT_E_TIMING
#define UFT_E_TIMING UFT_ERR_TIMING
#endif
#ifndef UFT_E_ID_MISMATCH
#define UFT_E_ID_MISMATCH UFT_ERR_ID_MISMATCH
#endif
#ifndef UFT_E_DELETED_DATA
#define UFT_E_DELETED_DATA UFT_ERR_DELETED_DATA
#endif
#ifndef UFT_E_MISSING_SECTOR
#define UFT_E_MISSING_SECTOR UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_E_INCOMPLETE
#define UFT_E_INCOMPLETE UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_E_PLL_UNLOCK
#define UFT_E_PLL_UNLOCK UFT_ERR_PLL_UNLOCK
#endif
#ifndef UFT_E_PROTECTION
#define UFT_E_PROTECTION UFT_ERR_PROTECTION
#endif
#ifndef UFT_E_COPY_DENIED
#define UFT_E_COPY_DENIED UFT_ERR_COPY_DENIED
#endif
#ifndef UFT_E_WRITE_PROTECT
#define UFT_E_WRITE_PROTECT UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_E_WRITE_FAULT
#define UFT_E_WRITE_FAULT UFT_ERR_WRITE_FAULT
#endif
#ifndef UFT_E_TRACK_OVERFLOW
#define UFT_E_TRACK_OVERFLOW UFT_ERR_TRACK_OVERFLOW
#endif
#ifndef UFT_E_VERIFY_FAIL
#define UFT_E_VERIFY_FAIL UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_E_FILE_OPEN
#define UFT_E_FILE_OPEN UFT_ERR_FILE_OPEN
#endif
#ifndef UFT_E_FILE_READ
#define UFT_E_FILE_READ UFT_ERR_FILE_READ
#endif
#ifndef UFT_E_FILE_CREATE
#define UFT_E_FILE_CREATE UFT_ERR_FILE_CREATE
#endif
#ifndef UFT_E_FILE_SEEK
#define UFT_E_FILE_SEEK UFT_ERR_FILE_SEEK
#endif
#ifndef UFT_E_FILE_WRITE
#define UFT_E_FILE_WRITE UFT_ERR_FILE_WRITE
#endif
#ifndef UFT_E_CANCELLED
#define UFT_E_CANCELLED UFT_ERR_CANCELLED
#endif
#ifndef UFT_E_INVALID_STATE
#define UFT_E_INVALID_STATE UFT_ERR_INVALID_STATE
#endif
#ifndef UFT_E_VERSION
#define UFT_E_VERSION UFT_ERR_VERSION
#endif
#ifndef UFT_E_PLUGIN_LOAD
#define UFT_E_PLUGIN_LOAD UFT_ERR_PLUGIN_LOAD
#endif
#ifndef UFT_E_PLUGIN_NOT_FOUND
#define UFT_E_PLUGIN_NOT_FOUND UFT_ERR_PLUGIN_NOT_FOUND
#endif

/* ------------------------------------------------------------------------ */
/* 3. Legacy aliases catalogued in data/errors_legacy_aliases.tsv           */
/*    (UFT_ERR_*, UFT_ERROR_*, UFT_E_*, UFT_IR_*, UFT_DEC_*, UFT_IO_*,      */
/*     UFT_E<short>). Grouped by prefix for readability.                    */
/* ------------------------------------------------------------------------ */

/* --- UFT_ERR_* --- */
#ifndef UFT_ERR_INVALID_PARAM
#define UFT_ERR_INVALID_PARAM UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERR_STATE
#define UFT_ERR_STATE UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERR_NULL_PTR
#define UFT_ERR_NULL_PTR UFT_ERR_NULL_POINTER
#endif
#ifndef UFT_ERR_BOUNDS
#define UFT_ERR_BOUNDS UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERR_VERIFY
#define UFT_ERR_VERIFY UFT_ERR_CRC
#endif
#ifndef UFT_ERR_UNSUPPORTED
#define UFT_ERR_UNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_ERR_NOMEM
#define UFT_ERR_NOMEM UFT_ERR_MEMORY
#endif
#ifndef UFT_ERR_NOT_FOUND
#define UFT_ERR_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_ERR_CORRUPT
#define UFT_ERR_CORRUPT UFT_ERR_CORRUPTED
#endif
#ifndef UFT_ERR_NOT_IMPL
#define UFT_ERR_NOT_IMPL UFT_ERR_NOT_IMPLEMENTED
#endif
#ifndef UFT_ERR_LIMIT
#define UFT_ERR_LIMIT UFT_ERR_MEMORY
#endif
#ifndef UFT_ERR_INVALID_PARAM_VALUE
#define UFT_ERR_INVALID_PARAM_VALUE UFT_ERR_INVALID_ARG
#endif

/* --- UFT_E<short> --- */
#ifndef UFT_ERC_FORMAT
#define UFT_ERC_FORMAT UFT_ERR_FORMAT
#endif

/* --- UFT_ERR_* --- */
#ifndef UFT_ERR_OUT_OF_MEMORY
#define UFT_ERR_OUT_OF_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_ERR_FORMAT_ERROR
#define UFT_ERR_FORMAT_ERROR UFT_ERR_FORMAT
#endif
#ifndef UFT_ERR_CRC_ERROR
#define UFT_ERR_CRC_ERROR UFT_ERR_CRC
#endif
#ifndef UFT_ERR_IO_ERROR
#define UFT_ERR_IO_ERROR UFT_ERR_IO
#endif
#ifndef UFT_ERR_NO_DATA
#define UFT_ERR_NO_DATA UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_ERR_OK
#define UFT_ERR_OK UFT_SUCCESS
#endif
#ifndef UFT_ERR_NO_MEMORY
#define UFT_ERR_NO_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_ERR_OUT_OF_RANGE
#define UFT_ERR_OUT_OF_RANGE UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERR_VERIFY_FAILED
#define UFT_ERR_VERIFY_FAILED UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_ERR_INVALID_FORMAT
#define UFT_ERR_INVALID_FORMAT UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERR_FORMAT_NOT_SUPPORTED
#define UFT_ERR_FORMAT_NOT_SUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_ERR_DISK_PROTECTED
#define UFT_ERR_DISK_PROTECTED UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_ERR_READ_ONLY
#define UFT_ERR_READ_ONLY UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_ERR_GEOMETRY_MISMATCH
#define UFT_ERR_GEOMETRY_MISMATCH UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERR_TRANSACTION_CONFLICT
#define UFT_ERR_TRANSACTION_CONFLICT UFT_ERR_BUSY
#endif

/* --- UFT_ERROR_* --- */
#ifndef UFT_ERROR_NO_MEMORY
#define UFT_ERROR_NO_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_ERROR_DISK_PROTECTED
#define UFT_ERROR_DISK_PROTECTED UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_ERROR_TRACK_NOT_FOUND
#define UFT_ERROR_TRACK_NOT_FOUND UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_ERROR_SECTOR_NOT_FOUND
#define UFT_ERROR_SECTOR_NOT_FOUND UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_ERROR_CRC_ERROR
#define UFT_ERROR_CRC_ERROR UFT_ERR_CRC
#endif
#ifndef UFT_ERROR_GEOMETRY_MISMATCH
#define UFT_ERROR_GEOMETRY_MISMATCH UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERROR_CONVERSION_LOSSY
#define UFT_ERROR_CONVERSION_LOSSY UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERROR_TRANSACTION_CONFLICT
#define UFT_ERROR_TRANSACTION_CONFLICT UFT_ERR_BUSY
#endif
#ifndef UFT_ERROR_TRANSACTION_LIMIT
#define UFT_ERROR_TRANSACTION_LIMIT UFT_ERR_RESOURCE
#endif
#ifndef UFT_ERROR_TOOL_FAILED
#define UFT_ERROR_TOOL_FAILED UFT_ERR_INTERNAL
#endif
#ifndef UFT_ERROR_UNKNOWN_ENCODING
#define UFT_ERROR_UNKNOWN_ENCODING UFT_ERR_ENCODING
#endif
#ifndef UFT_ERROR_OUT_OF_RANGE
#define UFT_ERROR_OUT_OF_RANGE UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERROR_ALLOC_FAILED
#define UFT_ERROR_ALLOC_FAILED UFT_ERR_MEMORY
#endif
#ifndef UFT_ERROR_FILE_CORRUPT
#define UFT_ERROR_FILE_CORRUPT UFT_ERR_CORRUPTED
#endif
#ifndef UFT_ERROR_FILE_TOO_LARGE
#define UFT_ERROR_FILE_TOO_LARGE UFT_ERR_IO
#endif
#ifndef UFT_ERROR_FILE_PERMISSION
#define UFT_ERROR_FILE_PERMISSION UFT_ERR_PERMISSION
#endif
#ifndef UFT_ERROR_FORMAT_UNKNOWN
#define UFT_ERROR_FORMAT_UNKNOWN UFT_ERR_UNKNOWN_FORMAT
#endif
#ifndef UFT_ERROR_FORMAT_MISMATCH
#define UFT_ERROR_FORMAT_MISMATCH UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERROR_DISK_READ
#define UFT_ERROR_DISK_READ UFT_ERR_IO
#endif
#ifndef UFT_ERROR_DISK_WRITE
#define UFT_ERROR_DISK_WRITE UFT_ERR_IO
#endif
#ifndef UFT_ERROR_DISK_NOTREADY
#define UFT_ERROR_DISK_NOTREADY UFT_ERR_TIMEOUT
#endif
#ifndef UFT_ERROR_TRACK_READ
#define UFT_ERROR_TRACK_READ UFT_ERR_IO
#endif
#ifndef UFT_ERROR_TRACK_WRITE
#define UFT_ERROR_TRACK_WRITE UFT_ERR_IO
#endif
#ifndef UFT_ERROR_BAD_CHECKSUM
#define UFT_ERROR_BAD_CHECKSUM UFT_ERR_CRC
#endif
#ifndef UFT_ERROR_BAD_HEADER
#define UFT_ERROR_BAD_HEADER UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERROR_BAD_MAGIC
#define UFT_ERROR_BAD_MAGIC UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERROR_DATA_CRC_ERROR
#define UFT_ERROR_DATA_CRC_ERROR UFT_ERR_CRC
#endif
#ifndef UFT_ERROR_DECODE_FAILED
#define UFT_ERROR_DECODE_FAILED UFT_ERR_ENCODING
#endif
#ifndef UFT_ERROR_DEVICE_BUSY
#define UFT_ERROR_DEVICE_BUSY UFT_ERR_BUSY
#endif
#ifndef UFT_ERROR_DEVICE_ERROR
#define UFT_ERROR_DEVICE_ERROR UFT_ERR_HARDWARE
#endif
#ifndef UFT_ERROR_DEVICE_OFFLINE
#define UFT_ERROR_DEVICE_OFFLINE UFT_ERR_HARDWARE
#endif
#ifndef UFT_ERROR_DISK_CHANGED
#define UFT_ERROR_DISK_CHANGED UFT_ERR_IO
#endif
#ifndef UFT_ERROR_DISK_FULL
#define UFT_ERROR_DISK_FULL UFT_ERR_IO
#endif
#ifndef UFT_ERROR_DISK_NOT_READY
#define UFT_ERROR_DISK_NOT_READY UFT_ERR_TIMEOUT
#endif
#ifndef UFT_ERROR_DISK_REMOVED
#define UFT_ERROR_DISK_REMOVED UFT_ERR_IO
#endif
#ifndef UFT_ERROR_DRIVE_BUSY
#define UFT_ERROR_DRIVE_BUSY UFT_ERR_BUSY
#endif
#ifndef UFT_ERROR_DRIVE_NOT_FOUND
#define UFT_ERROR_DRIVE_NOT_FOUND UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_ERROR_ENCODE_FAILED
#define UFT_ERROR_ENCODE_FAILED UFT_ERR_ENCODING
#endif
#ifndef UFT_ERROR_FORMAT_CONVERT
#define UFT_ERROR_FORMAT_CONVERT UFT_ERR_FORMAT
#endif
#ifndef UFT_ERROR_FORMAT_VERSION
#define UFT_ERROR_FORMAT_VERSION UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_ERROR_FUZZY_BITS
#define UFT_ERROR_FUZZY_BITS UFT_ERR_WEAK_BITS
#endif
#ifndef UFT_ERROR_ID_CRC_ERROR
#define UFT_ERROR_ID_CRC_ERROR UFT_ERR_CRC
#endif
#ifndef UFT_ERROR_MOTOR_ERROR
#define UFT_ERROR_MOTOR_ERROR UFT_ERR_HARDWARE
#endif
#ifndef UFT_ERROR_NO_DISK
#define UFT_ERROR_NO_DISK UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_ERROR_NO_INDEX
#define UFT_ERROR_NO_INDEX UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_ERROR_NO_SYNC
#define UFT_ERROR_NO_SYNC UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_ERROR_PLL_FAILED
#define UFT_ERROR_PLL_FAILED UFT_ERR_PLL_UNLOCK
#endif
#ifndef UFT_ERROR_PLUGIN_INIT
#define UFT_ERROR_PLUGIN_INIT UFT_ERR_PLUGIN_LOAD
#endif
#ifndef UFT_ERROR_PLUGIN_VERSION
#define UFT_ERROR_PLUGIN_VERSION UFT_ERR_VERSION
#endif
#ifndef UFT_ERROR_READ_PROTECTED
#define UFT_ERROR_READ_PROTECTED UFT_ERR_NOT_PERMITTED
#endif
#ifndef UFT_ERROR_SEEK_ERROR
#define UFT_ERROR_SEEK_ERROR UFT_ERR_FILE_SEEK
#endif
#ifndef UFT_ERROR_STACK_OVERFLOW
#define UFT_ERROR_STACK_OVERFLOW UFT_ERR_MEMORY
#endif
#ifndef UFT_ERROR_UNFORMATTED
#define UFT_ERROR_UNFORMATTED UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERROR_USB_ERROR
#define UFT_ERROR_USB_ERROR UFT_ERR_USB
#endif
#ifndef UFT_ERROR_VERIFY_FAILED
#define UFT_ERROR_VERIFY_FAILED UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_ERROR_DISK_NOT_OPEN
#define UFT_ERROR_DISK_NOT_OPEN UFT_ERR_INVALID_STATE
#endif
#ifndef UFT_ERROR_FORMAT_UNSUPPORTED
#define UFT_ERROR_FORMAT_UNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_ERROR_INVALID_ARGUMENT
#define UFT_ERROR_INVALID_ARGUMENT UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERROR_OVERFLOW
#define UFT_ERROR_OVERFLOW UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERROR_DECODE
#define UFT_ERROR_DECODE UFT_ERR_ENCODING
#endif
#ifndef UFT_ERROR_INVALID_FORMAT
#define UFT_ERROR_INVALID_FORMAT UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_ERROR_NO_DATA
#define UFT_ERROR_NO_DATA UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_ERROR_NOT_FOUND
#define UFT_ERROR_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_ERROR_INVALID_PARAM
#define UFT_ERROR_INVALID_PARAM UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_ERROR_FORMAT_NOT_SUPPORTED
#define UFT_ERROR_FORMAT_NOT_SUPPORTED UFT_ERR_NOT_SUPPORTED
#endif

/* --- UFT_IO_* --- */
#ifndef UFT_IO_ERR_READ
#define UFT_IO_ERR_READ UFT_ERR_IO
#endif
#ifndef UFT_IO_ERR_WRITE
#define UFT_IO_ERR_WRITE UFT_ERR_IO
#endif
#ifndef UFT_IO_ERR_EOF
#define UFT_IO_ERR_EOF UFT_ERR_EOF
#endif

/* --- UFT_IR_* --- */
#ifndef UFT_IR_ERR_READ
#define UFT_IR_ERR_READ UFT_ERR_IO
#endif

/* --- UFT_E<short> --- */
#ifndef UFT_EINVAL
#define UFT_EINVAL UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_EIO
#define UFT_EIO UFT_ERR_IO
#endif
#ifndef UFT_EFORMAT
#define UFT_EFORMAT UFT_ERR_FORMAT
#endif
#ifndef UFT_EUNSUPPORTED
#define UFT_EUNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_ENOMEM
#define UFT_ENOMEM UFT_ERR_MEMORY
#endif
#ifndef UFT_ECRC
#define UFT_ECRC UFT_ERR_CRC
#endif
#ifndef UFT_ENOT_IMPLEMENTED
#define UFT_ENOT_IMPLEMENTED UFT_ERR_NOT_IMPLEMENTED
#endif
#ifndef UFT_ETIMEOUT
#define UFT_ETIMEOUT UFT_ERR_TIMEOUT
#endif

/* --- UFT_E_* --- */
#ifndef UFT_E_GENERIC
#define UFT_E_GENERIC UFT_ERR_INTERNAL
#endif
#ifndef UFT_E_NULL_PTR
#define UFT_E_NULL_PTR UFT_ERR_NULL_POINTER
#endif
#ifndef UFT_E_NOT_FOUND
#define UFT_E_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_E_ALREADY_EXISTS
#define UFT_E_ALREADY_EXISTS UFT_ERR_FILE_EXISTS
#endif
#ifndef UFT_E_OVERFLOW
#define UFT_E_OVERFLOW UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_UNDERFLOW
#define UFT_E_UNDERFLOW UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_RANGE
#define UFT_E_RANGE UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_STATE
#define UFT_E_STATE UFT_ERR_INVALID_STATE
#endif
#ifndef UFT_E_LOCKED
#define UFT_E_LOCKED UFT_ERR_BUSY
#endif
#ifndef UFT_E_SECURITY
#define UFT_E_SECURITY UFT_ERR_INVALID_PATH
#endif
#ifndef UFT_E_FILE_CLOSE
#define UFT_E_FILE_CLOSE UFT_ERR_IO
#endif
#ifndef UFT_E_FILE_DELETE
#define UFT_E_FILE_DELETE UFT_ERR_IO
#endif
#ifndef UFT_E_FILE_TOO_LARGE
#define UFT_E_FILE_TOO_LARGE UFT_ERR_IO
#endif
#ifndef UFT_E_FILE_TOO_SMALL
#define UFT_E_FILE_TOO_SMALL UFT_ERR_IO
#endif
#ifndef UFT_E_FILE_TRUNCATED
#define UFT_E_FILE_TRUNCATED UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_E_PATH_INVALID
#define UFT_E_PATH_INVALID UFT_ERR_INVALID_PATH
#endif
#ifndef UFT_E_PATH_TOO_LONG
#define UFT_E_PATH_TOO_LONG UFT_ERR_INVALID_PATH
#endif
#ifndef UFT_E_DIR_NOT_FOUND
#define UFT_E_DIR_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_E_DIR_NOT_EMPTY
#define UFT_E_DIR_NOT_EMPTY UFT_ERR_IO
#endif
#ifndef UFT_E_DISK_FULL
#define UFT_E_DISK_FULL UFT_ERR_IO
#endif
#ifndef UFT_E_READ_ONLY
#define UFT_E_READ_ONLY UFT_ERR_WRITE_PROTECT
#endif
#ifndef UFT_E_FORMAT_UNKNOWN
#define UFT_E_FORMAT_UNKNOWN UFT_ERR_UNKNOWN_FORMAT
#endif
#ifndef UFT_E_FORMAT_UNSUPPORTED
#define UFT_E_FORMAT_UNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_E_FORMAT_VERSION
#define UFT_E_FORMAT_VERSION UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_E_MAGIC
#define UFT_E_MAGIC UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_E_HEADER
#define UFT_E_HEADER UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_E_CHECKSUM
#define UFT_E_CHECKSUM UFT_ERR_CRC
#endif
#ifndef UFT_E_CORRUPT
#define UFT_E_CORRUPT UFT_ERR_CORRUPTED
#endif
#ifndef UFT_E_TRUNCATED
#define UFT_E_TRUNCATED UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_E_PARSE
#define UFT_E_PARSE UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_E_SYNTAX
#define UFT_E_SYNTAX UFT_ERR_FORMAT_INVALID
#endif
#ifndef UFT_E_COMPRESSION
#define UFT_E_COMPRESSION UFT_ERR_FORMAT
#endif
#ifndef UFT_E_DECOMPRESSION
#define UFT_E_DECOMPRESSION UFT_ERR_FORMAT
#endif
#ifndef UFT_E_DECODE
#define UFT_E_DECODE UFT_ERR_ENCODING
#endif
#ifndef UFT_E_DECODE_SYNC
#define UFT_E_DECODE_SYNC UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_E_DECODE_IDAM
#define UFT_E_DECODE_IDAM UFT_ERR_ID_MISMATCH
#endif
#ifndef UFT_E_DECODE_DAM
#define UFT_E_DECODE_DAM UFT_ERR_MISSING_SECTOR
#endif
#ifndef UFT_E_DECODE_CRC
#define UFT_E_DECODE_CRC UFT_ERR_CRC
#endif
#ifndef UFT_E_DECODE_BITSLIP
#define UFT_E_DECODE_BITSLIP UFT_ERR_ENCODING
#endif
#ifndef UFT_E_DECODE_PLL
#define UFT_E_DECODE_PLL UFT_ERR_PLL_UNLOCK
#endif
#ifndef UFT_E_DECODE_WEAK
#define UFT_E_DECODE_WEAK UFT_ERR_WEAK_BITS
#endif
#ifndef UFT_E_DECODE_SPLICE
#define UFT_E_DECODE_SPLICE UFT_ERR_TIMING
#endif
#ifndef UFT_E_DECODE_DENSITY
#define UFT_E_DECODE_DENSITY UFT_ERR_TIMING
#endif
#ifndef UFT_E_DECODE_TIMING
#define UFT_E_DECODE_TIMING UFT_ERR_TIMING
#endif
#ifndef UFT_E_ENCODE
#define UFT_E_ENCODE UFT_ERR_ENCODING
#endif
#ifndef UFT_E_ENCODE_OVERFLOW
#define UFT_E_ENCODE_OVERFLOW UFT_ERR_TRACK_OVERFLOW
#endif
#ifndef UFT_E_NOT_DETECTED
#define UFT_E_NOT_DETECTED UFT_ERR_FORMAT_DETECT
#endif
#ifndef UFT_E_NOT_REGISTERED
#define UFT_E_NOT_REGISTERED UFT_ERR_PLUGIN_NOT_FOUND
#endif
#ifndef UFT_E_HW_NOT_FOUND
#define UFT_E_HW_NOT_FOUND UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_E_HW_OPEN
#define UFT_E_HW_OPEN UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_HW_CLOSE
#define UFT_E_HW_CLOSE UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_HW_TIMEOUT
#define UFT_E_HW_TIMEOUT UFT_ERR_TIMEOUT
#endif
#ifndef UFT_E_HW_BUSY
#define UFT_E_HW_BUSY UFT_ERR_BUSY
#endif
#ifndef UFT_E_HW_RESET
#define UFT_E_HW_RESET UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_HW_COMM
#define UFT_E_HW_COMM UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_HW_PROTOCOL
#define UFT_E_HW_PROTOCOL UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_HW_FIRMWARE
#define UFT_E_HW_FIRMWARE UFT_ERR_VERSION
#endif
#ifndef UFT_E_DRIVE_NOT_READY
#define UFT_E_DRIVE_NOT_READY UFT_ERR_TIMEOUT
#endif
#ifndef UFT_E_NO_DISK
#define UFT_E_NO_DISK UFT_ERR_DEVICE_NOT_FOUND
#endif
#ifndef UFT_E_SEEK
#define UFT_E_SEEK UFT_ERR_FILE_SEEK
#endif
#ifndef UFT_E_INDEX
#define UFT_E_INDEX UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_E_MOTOR
#define UFT_E_MOTOR UFT_ERR_HARDWARE
#endif
#ifndef UFT_E_NOMEM
#define UFT_E_NOMEM UFT_ERR_MEMORY
#endif
#ifndef UFT_E_ALLOC
#define UFT_E_ALLOC UFT_ERR_MEMORY
#endif
#ifndef UFT_E_REALLOC
#define UFT_E_REALLOC UFT_ERR_MEMORY
#endif
#ifndef UFT_E_FREE
#define UFT_E_FREE UFT_ERR_INTERNAL
#endif
#ifndef UFT_E_LEAK
#define UFT_E_LEAK UFT_ERR_INTERNAL
#endif
#ifndef UFT_E_ALIGNMENT
#define UFT_E_ALIGNMENT UFT_ERR_INTERNAL
#endif
#ifndef UFT_E_STACK
#define UFT_E_STACK UFT_ERR_MEMORY
#endif
#ifndef UFT_E_PROT_DETECTED
#define UFT_E_PROT_DETECTED UFT_ERR_PROTECTION
#endif
#ifndef UFT_E_PROT_UNSUPPORTED
#define UFT_E_PROT_UNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif
#ifndef UFT_E_PROT_INCOMPLETE
#define UFT_E_PROT_INCOMPLETE UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_E_PROT_VERIFY
#define UFT_E_PROT_VERIFY UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_E_VALIDATION
#define UFT_E_VALIDATION UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_VERIFY
#define UFT_E_VERIFY UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_E_MISMATCH
#define UFT_E_MISMATCH UFT_ERR_VERIFY_FAIL
#endif
#ifndef UFT_E_HASH
#define UFT_E_HASH UFT_ERR_CRC
#endif
#ifndef UFT_E_SIGNATURE
#define UFT_E_SIGNATURE UFT_ERR_CRC
#endif
#ifndef UFT_E_BOUNDS
#define UFT_E_BOUNDS UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_E_CONSTRAINT
#define UFT_E_CONSTRAINT UFT_ERR_INVALID_ARG
#endif

/* --- UFT_IR_* --- */
#ifndef UFT_IR_OK
#define UFT_IR_OK UFT_SUCCESS
#endif
#ifndef UFT_IR_ERR_NOMEM
#define UFT_IR_ERR_NOMEM UFT_ERR_MEMORY
#endif
#ifndef UFT_IR_ERR_INVALID
#define UFT_IR_ERR_INVALID UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_IR_ERR_OVERFLOW
#define UFT_IR_ERR_OVERFLOW UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_IR_ERR_IO
#define UFT_IR_ERR_IO UFT_ERR_IO
#endif
#ifndef UFT_IR_ERR_FORMAT
#define UFT_IR_ERR_FORMAT UFT_ERR_FORMAT
#endif
#ifndef UFT_IR_ERR_VERSION
#define UFT_IR_ERR_VERSION UFT_ERR_FORMAT_VARIANT
#endif
#ifndef UFT_IR_ERR_CHECKSUM
#define UFT_IR_ERR_CHECKSUM UFT_ERR_CRC
#endif
#ifndef UFT_IR_ERR_COMPRESSION
#define UFT_IR_ERR_COMPRESSION UFT_ERR_FORMAT
#endif
#ifndef UFT_IR_ERR_NOT_FOUND
#define UFT_IR_ERR_NOT_FOUND UFT_ERR_FILE_NOT_FOUND
#endif
#ifndef UFT_IR_ERR_DUPLICATE
#define UFT_IR_ERR_DUPLICATE UFT_ERR_FILE_EXISTS
#endif
#ifndef UFT_IR_ERR_CORRUPT
#define UFT_IR_ERR_CORRUPT UFT_ERR_CORRUPTED
#endif

/* --- UFT_DEC_* --- */
#ifndef UFT_DEC_OK
#define UFT_DEC_OK UFT_SUCCESS
#endif
#ifndef UFT_DEC_ERR_INVALID_ARG
#define UFT_DEC_ERR_INVALID_ARG UFT_ERR_INVALID_ARG
#endif
#ifndef UFT_DEC_ERR_NO_MEMORY
#define UFT_DEC_ERR_NO_MEMORY UFT_ERR_MEMORY
#endif
#ifndef UFT_DEC_ERR_NOT_DETECTED
#define UFT_DEC_ERR_NOT_DETECTED UFT_ERR_FORMAT_DETECT
#endif
#ifndef UFT_DEC_ERR_DECODE_FAILED
#define UFT_DEC_ERR_DECODE_FAILED UFT_ERR_ENCODING
#endif
#ifndef UFT_DEC_ERR_ENCODE_FAILED
#define UFT_DEC_ERR_ENCODE_FAILED UFT_ERR_ENCODING
#endif
#ifndef UFT_DEC_ERR_CRC_ERROR
#define UFT_DEC_ERR_CRC_ERROR UFT_ERR_CRC
#endif
#ifndef UFT_DEC_ERR_NO_SYNC
#define UFT_DEC_ERR_NO_SYNC UFT_ERR_SYNC_LOST
#endif
#ifndef UFT_DEC_ERR_TRUNCATED
#define UFT_DEC_ERR_TRUNCATED UFT_ERR_INCOMPLETE
#endif
#ifndef UFT_DEC_ERR_NOT_REGISTERED
#define UFT_DEC_ERR_NOT_REGISTERED UFT_ERR_PLUGIN_NOT_FOUND
#endif
#ifndef UFT_DEC_ERR_UNSUPPORTED
#define UFT_DEC_ERR_UNSUPPORTED UFT_ERR_NOT_SUPPORTED
#endif

#ifdef UFT_WARN_LEGACY_ERROR_ALIASES
#  if defined(__GNUC__) || defined(__clang__)
#    pragma GCC warning "UFT_ERR_* / UFT_ERROR_* legacy aliases are deprecated; use UFT_ERR_<NAME> directly."
#  endif
#endif

#ifdef __cplusplus
}
#endif

#endif /* UFT_ERROR_COMPAT_GEN_H */
