#ifndef UFT_LOADERS_IPF_LOADER_IPF_WRITER_H
#define UFT_LOADERS_IPF_LOADER_IPF_WRITER_H

int IPF_libWrite_DiskFile(LIBFLUX_IMGLDR* imgldr_ctx,LIBFLUX_FLOPPY * floppy,char * filename);

#endif /* UFT_LOADERS_IPF_LOADER_IPF_WRITER_H */
