/**
 * @file uft_format_plugin.c
 * @brief UnifiedFloppyTool - Format Plugin Registry
 * 
 * Verwaltet Format-Plugins und bietet Auto-Detection.
 * 
 * @author UFT Team
 * @date 2025
 */

#include "uft/uft_format_plugin.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "uft/uft_compat.h"  /* strcasecmp */

// ============================================================================
// Plugin Registry
// ============================================================================

/* MF-445: was 32. The tree defines 137 plugins, so uft_register_all_formats()
 * would have filled the table and then returned UFT_ERROR_BUFFER_TOO_SMALL for
 * the remaining 105 — the third gate in a row that silently capped the registry
 * far below the plugin count (the other two: duplicate-check on .format, and
 * having no caller at all; see ARCH-9).
 *
 * MF-446: 128 was still too small. The count is not 88 but 137 — 88 written out
 * and 49 generated by the DSK_PLUGIN() macro in src/formats/dsk_generic/, which
 * the MF-445 gate could not see because it only matched written-out definitions.
 * A gate that undercounts is worse than none: it reported "fits" while nine
 * plugins would have been refused. The gate counts the macro now too.
 *
 * 192 leaves room for ~55 more. */
#define MAX_FORMAT_PLUGINS 192

static const uft_format_plugin_t* g_format_plugins[MAX_FORMAT_PLUGINS] = {0};
static size_t g_format_plugin_count = 0;

// ============================================================================
// Registration
// ============================================================================

uft_error_t uft_register_format_plugin(const uft_format_plugin_t* plugin) {
    if (!plugin) return UFT_ERROR_NULL_POINTER;
    if (!plugin->name) return UFT_ERROR_INVALID_ARG;

    /* UFT-004 (v4.1.5-hardening) ABI gate.
     * api_version == 0 ⇒ legacy plugin (pre-v4.1.5), accepted with stderr
     *                    warning so the gap is visible in the build log.
     * api_version > UFT_PLUGIN_API_VERSION ⇒ plugin compiled against a newer
     *                    header than the running host. Reject — silent
     *                    layout drift is exactly the bomb we want to avoid.
     */
    if (plugin->api_version > UFT_PLUGIN_API_VERSION) {
        fprintf(stderr,
                "[UFT] reject plugin '%s': api_version=%u > host=%u (rebuild plugin against current headers)\n",
                plugin->name, plugin->api_version, UFT_PLUGIN_API_VERSION);
        return UFT_ERROR_PLUGIN_LOAD;
    }
    if (plugin->api_version == 0u) {
        /* One-shot warning — 80 plugins registering at startup would
         * otherwise spam stderr with the same message 80 times. The
         * actual migration trigger is the v5.0 reject; this is just
         * a developer reminder. */
        static int s_legacy_warned = 0;
        if (!s_legacy_warned) {
            s_legacy_warned = 1;
            fprintf(stderr,
                    "[UFT] note: one or more plugins have api_version=0 "
                    "(legacy). First seen: '%s'. Plugins must set "
                    ".api_version = UFT_PLUGIN_API_VERSION before v5.0.\n",
                    plugin->name);
        }
    }

    /* Duplikate prüfen — auf .name, nicht auf .format (MF-444).
     *
     * This test used to read `g_format_plugins[i]->format == plugin->format`.
     * 131 of the 137 plugins in the tree declare `.format = UFT_FORMAT_DSK`,
     * because that enum names a container class ("a sector image"), not a
     * format. The registry therefore accepted the first DSK plugin and rejected
     * the other 130, silently, with the same error code used for a plugin that
     * is genuinely broken. Registration could never hold more than 7 of 137.
     *
     * That is why nothing in the tree calls uft_register_all_formats(): every
     * consumer grew around the registry by linking plugin symbols directly.
     *
     * `.name` is unique across all 137 and is what identifies a plugin. Two
     * plugins sharing a container id is normal and must not be an error. */
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        if (g_format_plugins[i]->name && plugin->name &&
            strcmp(g_format_plugins[i]->name, plugin->name) == 0) {
            return UFT_ERROR_PLUGIN_LOAD;
        }
    }
    
    if (g_format_plugin_count >= MAX_FORMAT_PLUGINS) {
        fprintf(stderr,
                "[UFT] reject plugin '%s': registry full at %d entries - raise "
                "MAX_FORMAT_PLUGINS in src/core/uft_format_plugin.c\n",
                plugin->name, MAX_FORMAT_PLUGINS);
        return UFT_ERROR_BUFFER_TOO_SMALL;
    }
    
    // Plugin initialisieren
    if (plugin->init) {
        uft_error_t err = plugin->init();
        if (UFT_FAILED(err)) {
            return err;
        }
    }
    
    g_format_plugins[g_format_plugin_count++] = plugin;
    
    return UFT_OK;
}

uft_error_t uft_unregister_format_plugin(uft_format_t format) {
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        if (g_format_plugins[i]->format == format) {
            // Plugin shutdown
            if (g_format_plugins[i]->shutdown) {
                g_format_plugins[i]->shutdown();
            }
            
            // Lücke schließen
            for (size_t j = i; j + 1 < g_format_plugin_count; j++) {
                g_format_plugins[j] = g_format_plugins[j + 1];
            }
            g_format_plugin_count--;
            g_format_plugins[g_format_plugin_count] = NULL;
            
            return UFT_OK;
        }
    }
    
    return UFT_ERROR_PLUGIN_NOT_FOUND;
}

// ============================================================================
// Lookup
// ============================================================================

/* First plugin declaring this container id.
 *
 * MF-444: with 131 plugins on UFT_FORMAT_DSK this is a first-match, not an
 * identification — the answer depends on registration order, and it is wrong
 * for 130 of the 131 whenever the caller meant a specific format. The callers in
 * src/core/uft_disk_*.c and uft_format_verify.c pass a uft_format_t and cannot
 * express more, so the ambiguity is theirs to lose, not this function's to
 * hide: it is stated here and tracked as ARCH-9 in docs/KNOWN_ISSUES.md.
 * Callers that know which plugin they want should use
 * uft_get_format_plugin_by_name(). */
const uft_format_plugin_t* uft_get_format_plugin(uft_format_t format) {
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        if (g_format_plugins[i]->format == format) {
            return g_format_plugins[i];
        }
    }
    return NULL;
}

/* Does this plugin claim `ext` (without the dot)?
 *
 * MF-445: replaces a strtok() loop over a 256-byte stack copy. strtok keeps its
 * cursor in static storage, so two threads walking the plugin list at once
 * interleaved each other's tokenisation — and the copy silently truncated any
 * extension list longer than 255 characters. This walks the string in place:
 * no copy, no truncation, no shared cursor. Separators are ';', ',' and
 * whitespace; a leading dot on either side is tolerated. */
static bool plugin_claims_extension(const uft_format_plugin_t* plugin,
                                    const char* ext) {
    if (!plugin || !plugin->extensions || !ext || !*ext) return false;
    if (*ext == '.') ext++;
    size_t want = strlen(ext);
    if (want == 0) return false;

    for (const char* s = plugin->extensions; *s; ) {
        while (*s == ';' || *s == ',' || *s == ' ' || *s == '	' || *s == '.') s++;
        if (!*s) break;
        const char* start = s;
        while (*s && *s != ';' && *s != ',' && *s != ' ' && *s != '	') s++;
        size_t len = (size_t)(s - start);
        if (len == want) {
            size_t i = 0;
            while (i < len &&
                   tolower((unsigned char)start[i]) == tolower((unsigned char)ext[i]))
                i++;
            if (i == len) return true;
        }
    }
    return false;
}

/* MF-445: resolve a target plugin without guessing.
 *
 * A uft_format_t alone cannot name a plugin — 131 of 137 carry UFT_FORMAT_DSK.
 * The ladder, each rung refusing to invent what it does not know:
 *
 *   1. the id, if exactly one registered plugin carries it
 *   2. the extension of path_hint, among the plugins carrying that id
 *   3. nothing
 *
 * Rung 2 deserves a word, because uft_smart_open() just LOST its extension
 * fallback (MF-444) and this looks like the same move reversed. It is not. In
 * smart_open the name of an existing file was used to make a claim about the
 * bytes inside it — evidence it is not. Here the file does not exist yet and
 * the caller is choosing what to write: "out.d81" is a statement of intent, and
 * intent is exactly what a target format is.
 *
 * candidates_out, when given, receives how many plugins carried the id — so a
 * caller that gets NULL can say "12 plugins claim this id" instead of the
 * indistinguishable "unsupported". */
const uft_format_plugin_t* uft_resolve_format_plugin(uft_format_t format,
                                                     const char* path_hint,
                                                     size_t* candidates_out) {
    size_t n = uft_count_format_plugins_for(format);
    if (candidates_out) *candidates_out = n;
    if (n == 0) return NULL;
    if (n == 1) return uft_get_format_plugin(format);

    if (!path_hint) return NULL;
    const char* dot = strrchr(path_hint, '.');
    if (!dot || !dot[1]) return NULL;

    const uft_format_plugin_t* hit = NULL;
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        const uft_format_plugin_t* pl = g_format_plugins[i];
        if (!pl || pl->format != format || !pl->extensions) continue;
        if (!plugin_claims_extension(pl, dot + 1)) continue;
        if (hit) return NULL;          /* two plugins claim it: still a guess */
        hit = pl;
    }
    return hit;
}

const uft_format_plugin_t* uft_disk_plugin(const uft_disk_t* disk) {
    if (!disk) return NULL;
    if (disk->plugin) return disk->plugin;

    /* No plugin recorded: the disk predates the field or was assembled by
     * hand. Resolve from the container id only when it can identify exactly
     * one plugin — a first match out of 82 would be a guess, and the caller
     * uses the result to touch plugin_data. */
    if (uft_count_format_plugins_for(disk->format) != 1) return NULL;
    return uft_get_format_plugin(disk->format);
}

size_t uft_count_format_plugins_for(uft_format_t format) {
    size_t n = 0;
    for (size_t i = 0; i < g_format_plugin_count; i++)
        if (g_format_plugins[i]->format == format) n++;
    return n;
}

const uft_format_plugin_t* uft_get_format_plugin_by_name(const char* name) {
    if (!name) return NULL;
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        if (g_format_plugins[i]->name &&
            strcmp(g_format_plugins[i]->name, name) == 0) {
            return g_format_plugins[i];
        }
    }
    return NULL;
}

/* ============================================================================
 * Plugin Probing — Buffer and File
 * ============================================================================ */

/* MF-448 (ARCH-13): one pass, and it keeps what the old loop threw away.
 *
 * The winner is unchanged and still deterministic — strict `>` means the first
 * registered plugin keeps a tie, exactly as before, so no caller sees a
 * different format than yesterday. What is new is that the tie is now
 * countable. On atrcopy_dos2sd.xfd four plugins answer 40; the old return value
 * could not distinguish that from a lone 40, and every consumer printed the
 * winner as though it had been identified. */
size_t uft_probe_buffer_ranked(const uint8_t *data, size_t size,
                               size_t file_size, uft_probe_ranking_t *result) {
    uft_probe_ranking_t r;
    memset(&r, 0, sizeof(r));

    if (data && size > 0) {
        for (size_t i = 0; i < g_format_plugin_count; i++) {
            const uft_format_plugin_t *p = g_format_plugins[i];
            if (!p || !p->probe) continue;
            int conf = 0;
            if (!p->probe(data, size, file_size, &conf)) continue;

            r.claimants++;
            if (conf > r.confidence) {
                /* the previous best becomes the runner-up */
                r.runner_up = r.winner;
                r.runner_up_confidence = r.confidence;
                r.winner = p;
                r.confidence = conf;
                r.tied = 1;
            } else if (conf == r.confidence && r.winner) {
                r.tied++;                       /* as good as the winner */
            } else if (conf > r.runner_up_confidence) {
                r.runner_up = p;
                r.runner_up_confidence = conf;
            }
        }
    }

    if (result) *result = r;
    return r.claimants;
}

size_t uft_probe_file_ranked(const char *path, uft_probe_ranking_t *result) {
    if (result) memset(result, 0, sizeof(*result));
    if (!path) return 0;

    FILE *f = fopen(path, "rb");
    if (!f) return 0;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return 0; }
    long fs = ftell(f);
    if (fs < 0) { fclose(f); return 0; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return 0; }

    size_t probe_size = ((size_t)fs < UFT_PROBE_BUFFER_SIZE)
                            ? (size_t)fs : UFT_PROBE_BUFFER_SIZE;
    uint8_t *buf = malloc(probe_size);
    if (!buf) { fclose(f); return 0; }
    if (fread(buf, 1, probe_size, f) != probe_size) {
        free(buf); fclose(f); return 0;
    }
    fclose(f);

    size_t n = uft_probe_buffer_ranked(buf, probe_size, (size_t)fs, result);
    free(buf);
    return n;
}

const uft_format_plugin_t* uft_probe_buffer_format(const uint8_t *data,
                                                     size_t size,
                                                     size_t file_size) {
    uft_probe_ranking_t r;
    uft_probe_buffer_ranked(data, size, file_size, &r);
    return r.winner;
}

const uft_format_plugin_t* uft_probe_file_format(const char *path) {
    if (!path) return NULL;
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;

    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long fs = ftell(f);
    if (fs < 0) { fclose(f); return NULL; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }

    size_t probe_size = ((size_t)fs < UFT_PROBE_BUFFER_SIZE)
                            ? (size_t)fs : UFT_PROBE_BUFFER_SIZE;
    uint8_t *buf = malloc(probe_size);
    if (!buf) { fclose(f); return NULL; }

    if (fread(buf, 1, probe_size, f) != probe_size) {
        free(buf); fclose(f); return NULL;
    }
    fclose(f);

    uft_probe_ranking_t r;
    uft_probe_buffer_ranked(buf, probe_size, (size_t)fs, &r);
    free(buf);
    return r.winner;
}

const uft_format_plugin_t* uft_find_format_plugin_by_extension(const char* ext) {
    if (!ext || !*ext) return NULL;
    
    // Punkt überspringen
    if (*ext == '.') ext++;
    
    for (size_t i = 0; i < g_format_plugin_count; i++) {
        if (plugin_claims_extension(g_format_plugins[i], ext))
            return g_format_plugins[i];
    }

    /* First match. 13 of the 104 extensions in the tree are claimed by more
     * than one plugin (".dsk" by 18), so for those the answer above is a pick,
     * not an identification — callers that must be right use
     * uft_resolve_format_plugin() or uft_get_format_plugin_by_name(). */
    return NULL;
}

/* uft_find_format_plugin_for_file() stood here until MF-449.
 *
 * It was the THIRD implementation of "probe a file": its own 4096-byte stack
 * buffer, its own copy of the best-confidence loop, and — after the loop — a
 * fallback that guessed the format from the file extension, the same guess
 * uft_smart_open() lost in MF-444 for claiming something about the content
 * from something that is not the content.
 *
 * It had no caller anywhere in the tree. Removed rather than kept in step with
 * uft_probe_file_ranked(), because three copies of one decision is how the
 * buffer sizes drifted apart in the first place (ARCH-15). */

size_t uft_registered_format_plugin_count(void) {
    return g_format_plugin_count;
}

size_t uft_list_format_plugins(const uft_format_plugin_t** plugins, size_t max) {
    if (!plugins || max == 0) return 0;
    
    size_t count = 0;
    for (size_t i = 0; i < g_format_plugin_count && count < max; i++) {
        plugins[count++] = g_format_plugins[i];
    }
    
    return count;
}

// ============================================================================
// Track Helpers
// ============================================================================

void uft_track_init(uft_track_t* track, int cylinder, int head) {
    if (!track) return;
    
    memset(track, 0, sizeof(*track));
    track->cylinder = cylinder;
    track->head = head;
}

uft_error_t uft_track_add_sector(uft_track_t* track, const uft_sector_t* sector) {
    if (!track || !sector) return UFT_ERROR_NULL_POINTER;
    
    // Kapazität prüfen/erweitern
    if (track->sector_count >= track->sector_capacity) {
        size_t new_cap = track->sector_capacity ? track->sector_capacity * 2 : 32;
        uft_sector_t* new_sectors = realloc(track->sectors, 
                                             new_cap * sizeof(uft_sector_t));
        if (!new_sectors) return UFT_ERROR_NO_MEMORY;
        
        track->sectors = new_sectors;
        track->sector_capacity = new_cap;
    }
    
    // Sektor kopieren
    uft_sector_t* dst = &track->sectors[track->sector_count];
    *dst = *sector;
    
    // Daten kopieren
    if (sector->data && sector->data_size > 0) {
        dst->data = malloc(sector->data_size);
        if (!dst->data) return UFT_ERROR_NO_MEMORY;
        memcpy(dst->data, sector->data, sector->data_size);
    }
    
    track->sector_count++;
    return UFT_OK;
}

uft_error_t uft_track_set_flux(uft_track_t* track, const uint32_t* flux, 
                                size_t count, uint32_t tick_ns) {
    if (!track) return UFT_ERROR_NULL_POINTER;
    
    // Alte Daten freigeben
    free(track->flux);
    track->flux = NULL;
    track->flux_count = 0;
    
    if (flux && count > 0) {
        track->flux = malloc(count * sizeof(uint32_t));
        if (!track->flux) return UFT_ERROR_NO_MEMORY;
        
        memcpy(track->flux, flux, count * sizeof(uint32_t));
        track->flux_count = count;
        track->flux_tick_ns = tick_ns;
    }
    
    return UFT_OK;
}

void uft_track_cleanup(uft_track_t* track) {
    if (!track) return;

    if (track->sectors) {
        for (size_t i = 0; i < track->sector_count; i++) {
            /* Use the canonical per-sector cleanup so confidence_map,
             * weak_mask, and timing_ns are also freed. The earlier
             * inline `free(sectors[i].data)` leaked those, which became
             * material after TA3 (commit 81922aa) started populating
             * weak_mask on ATX reads — every disk-verify or stream
             * read on a weak-bit-bearing image would leak per-sector
             * forensic state. Mirror of uft_sector_cleanup parity-fix
             * applied in the same TA3 commit. */
            uft_sector_cleanup(&track->sectors[i]);
        }
        free(track->sectors);
    }

    free(track->flux);
    free(track->raw_data);

    memset(track, 0, sizeof(*track));
}

uft_error_t uft_sector_copy_plugin(uft_sector_t* dst, const uft_sector_t* src) {
    if (!dst || !src) return UFT_ERROR_NULL_POINTER;
    
    *dst = *src;
    dst->data = NULL;
    
    if (src->data && src->data_size > 0) {
        dst->data = malloc(src->data_size);
        if (!dst->data) return UFT_ERROR_NO_MEMORY;
        memcpy(dst->data, src->data, src->data_size);
    }
    
    return UFT_OK;
}

void uft_sector_cleanup(uft_sector_t* sector) {
    if (!sector) return;
    /* Free all heap-owned pointers — keep parity with uft_sector_free()
     * in uft_unified_types.c. Plugins that populate confidence_map,
     * weak_mask or timing_ns (e.g. ATX after TA3) would otherwise leak
     * when the sector is destroyed via this path. */
    free(sector->data);
    free(sector->confidence_map);
    free(sector->weak_mask);
    free(sector->timing_ns);
    memset(sector, 0, sizeof(*sector));
}

// ============================================================================
// Built-in Plugin Registration
// ============================================================================

/* INTENTIONAL-NOOP: built-in plugins are registered via the format
 * handler system in src/formats/uft_format_registry.c since the
 * registry consolidation. This function stays as an API-compat shim
 * for older callers — returning UFT_OK is CORRECT here because the
 * promised work (register built-ins) has already happened elsewhere
 * by the time any caller runs. Detector: the INTENTIONAL-NOOP marker
 * exempts this body from the lazy-stub pattern check in
 * scripts/check_consistency.py. */
uft_error_t uft_register_builtin_format_plugins(void) {
    return UFT_OK;
}

// ============================================================================
// Prinzip 7 — Spec-Status Helpers
// ============================================================================

const char* uft_spec_status_string(uft_spec_status_t status) {
    switch (status) {
        case UFT_SPEC_OFFICIAL_FULL:      return "OFFICIAL-FULL";
        case UFT_SPEC_OFFICIAL_PARTIAL:   return "OFFICIAL-PARTIAL";
        case UFT_SPEC_REVERSE_ENGINEERED: return "REVERSE-ENGINEERED";
        case UFT_SPEC_DERIVED:            return "DERIVED";
        case UFT_SPEC_UNKNOWN:            /* fallthrough */
        default:                          return "UNKNOWN";
    }
}

const char* uft_feature_support_string(uft_feature_support_t s) {
    switch (s) {
        case UFT_FEATURE_SUPPORTED:   return "SUPPORTED";
        case UFT_FEATURE_PARTIAL:     return "PARTIAL";
        case UFT_FEATURE_UNSUPPORTED: /* fallthrough */
        default:                      return "UNSUPPORTED";
    }
}

const char* uft_emu_compat_string(uft_emu_compat_t c) {
    switch (c) {
        case UFT_EMU_COMPATIBLE:   return "COMPATIBLE";
        case UFT_EMU_INCOMPATIBLE: return "INCOMPATIBLE";
        case UFT_EMU_PARTIAL:      return "PARTIAL";
        case UFT_EMU_UNTESTED:     /* fallthrough */
        default:                   return "UNTESTED";
    }
}
