#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=4

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS_DIR="$REPO_DIR/tests/corpus/_tools"
T98_DIR="$TOOLS_DIR/t98next/next_rb131"
TARGET_NFD="$REPO_DIR/tests/corpus/t98next_blank_2hd.nfd"
WAYBACK_URL="http://web.archive.org/web/20111124123056id_/http://www.geocities.jp/t98next/download/next_rb131.lzh"

find_7z() {
  if command -v 7z >/dev/null 2>&1; then echo "7z"; return 0; fi
  if [[ -x "/c/Program Files/7-Zip/7z.exe" ]]; then echo "/c/Program Files/7-Zip/7z.exe"; return 0; fi
  return 1
}

banner "T98-Next: Blank-NFD fuer das UFT-Korpus erzeugen"

# ── Stage 1: Werkzeug bereitstellen (automatisch) ─────────────────────────
stage "T98-Next herunterladen & entpacken (automatisch)"
say "T98-Next ist der EINZIGE Erzeuger des NFD-Formats (Recherche MF-367:"
say "gw/NP2kai/np21w/DOSBox-X/MAME/DiskExplorer koennen es alle nicht)."
say "Die Original-Site ist tot; wir laden das Archiv aus der Wayback Machine."
note "Lizenz T98-Next: Weiterverbreitung untersagt -> bleibt lokal in"
note "tests/corpus/_tools/ (gitignored), kommt NIE ins Repo."
SEVENZ="$(find_7z)" || { warn "7-Zip nicht gefunden (fuer .lzh noetig) - bitte installieren und neu starten."; exit 1; }
if [[ -x "$T98_DIR/Next.EXE" ]]; then
  note "bereits vorhanden: $T98_DIR - Download uebersprungen."
else
  mkdir -p "$TOOLS_DIR/t98next"
  say "Lade next_rb131.lzh (ca. 476 KB) ..."
  curl -fsSL "$WAYBACK_URL" -o "$TOOLS_DIR/t98next/next_rb131.lzh" \
    || { warn "Download fehlgeschlagen - Netz pruefen, dann neu starten."; exit 1; }
  "$SEVENZ" x -y -o"$TOOLS_DIR/t98next" "$TOOLS_DIR/t98next/next_rb131.lzh" >/dev/null \
    || { warn "Entpacken fehlgeschlagen."; exit 1; }
  [[ -x "$T98_DIR/Next.EXE" ]] || { warn "Next.EXE nicht gefunden nach Entpacken."; exit 1; }
  printf '  %s\n' "✓ entpackt nach $T98_DIR"
fi
pause

# ── Stage 2: T98-Next starten ─────────────────────────────────────────────
stage "T98-Next starten"
say "Ich starte jetzt Next.EXE. Wichtig zu wissen:"
step "Es koennen Fehlermeldungen wegen fehlender BIOS-ROMs erscheinen -"
step "einfach mit OK wegklicken. Fuer das Disk-Menue brauchen wir KEINE ROMs."
warn "Falls sich das Programm gar nicht oeffnet oder sofort beendet:"
note "  Ctrl-C hier druecken und Claude melden -> Plan C (PD-NFD-Suche)."
pause "Enter zum Starten von T98-Next ..."
( cd "$T98_DIR" && ./Next.EXE >/dev/null 2>&1 & )
say "T98-Next sollte sich jetzt oeffnen (2002er-GUI, evtl. hinter diesem Fenster)."
pause "Wenn das T98-Next-Fenster sichtbar ist: Enter."

# ── Stage 3: Blank-NFD im GUI erzeugen ────────────────────────────────────
stage "Blank-NFD erzeugen (deine 2 Minuten im GUI)"
say "Jetzt der eigentliche Handgriff. Die exakte Menuefuehrung des 2002er-GUIs"
say "kann leicht abweichen - im Programm existiert ein 'New'-Dialog fuer"
say "FD-Images (im Binary verifiziert: 'New', Signaturen R0+R1, 1.2M/1.44M)."
step "1. Suche die FDD-Anzeige: Leiste/Buttons 'FD Drive 1' / 'FDD1' (oder Menue)."
step "2. Klicke darauf (oder Rechtsklick) -> Eintrag 'New' waehlen."
step "3. Medientyp: 2HD / 1.2MB waehlen (PC-98-Standard)."
step "4. Falls nach dem Format gefragt wird: 'T98FDDIMAGE.R0' bzw. 'r0' waehlen."
note "   (r1 ist auch ok - beide sind implementiert; r0 ist das Prioritaetsziel)"
step "5. Speichern als:  t98next_blank_2hd.nfd"
step "   Ort ist egal - merke dir nur, WO du gespeichert hast."
note "Tipp: der Datei-Dialog startet meist im T98-Next-Verzeichnis:"
note "  $T98_DIR"
say ""
say "Danach kannst du T98-Next schliessen."
pause "Wenn die .nfd-Datei gespeichert ist: Enter."

# ── Stage 4: Verifizieren & einsammeln ────────────────────────────────────
stage "NFD verifizieren & ins Korpus legen"
DEFAULT_GUESS="$T98_DIR/t98next_blank_2hd.nfd"
NFD_SRC=""
if [[ -f "$TARGET_NFD" ]]; then
  NFD_SRC="$TARGET_NFD"
elif [[ -f "$DEFAULT_GUESS" ]]; then
  NFD_SRC="$DEFAULT_GUESS"
  note "gefunden: $DEFAULT_GUESS"
else
  say "Wo liegt die gespeicherte Datei? (kompletten Pfad einfuegen,"
  say "Windows-Pfade wie C:\...\datei.nfd sind ok)"
  ask NFD_PATH "Pfad zur .nfd:"
  NFD_SRC="$(printf '%s' "$NFD_PATH" | sed -e 's|\|/|g' -e 's|^\([A-Za-z]\):|/\L\1|')"
fi
[[ -f "$NFD_SRC" ]] || { warn "Datei nicht gefunden: $NFD_SRC - Wizard neu starten."; exit 1; }

SIG="$(head -c 14 "$NFD_SRC" | tr -d '\0')"
case "$SIG" in
  "T98FDDIMAGE.R0") say "✓ Signatur: NFD r0 (Prioritaetsziel!)" ;;
  "T98FDDIMAGE.R1") say "✓ Signatur: NFD r1 (auch gut - implementiert seit MF-360)" ;;
  *) warn "Unerwartete Signatur: '$SIG' - das ist kein NFD. Claude melden."; exit 1 ;;
esac

mkdir -p "$REPO_DIR/tests/corpus"
if [[ "$NFD_SRC" != "$TARGET_NFD" ]]; then
  cp "$NFD_SRC" "$TARGET_NFD"
fi
SIZE=$(wc -c < "$TARGET_NFD")
HASH=$(sha256sum "$TARGET_NFD" | cut -d' ' -f1)
say "Datei:  $TARGET_NFD"
say "Groesse: $SIZE Bytes"
say "SHA-256: $HASH"
say ""
printf '  %s%s✓ Fertig!%s Sag Claude jetzt einfach: %s"NFD liegt da"%s\n' "$BOLD" "$GREEN" "$RESET" "$BOLD" "$RESET"
note "Claude pinnt dann die Ground-Truth-Bytes, schreibt den Korpus-Test,"
note "traegt Hash+Herkunft ins Manifest ein und hebt NFD auf T1b."

finish
