#pragma once
/*
 * flux_consensus.h — Multi-rev consensus + sync-anchored windowing
 *
 * Prinzip:
 *   "Wir bewahren Information – wir entscheiden nicht vorschnell, was wichtig ist."
 *
 * Idee:
 *   - Mehrere Revolutionen eines Tracks enthalten unterschiedliche Jitter/Dropouts.
 *   - Statt "beste" Revolution zu wählen, richten wir jede Rev an einem
 *     stabilen Sync-Anker (0x4489) aus und bilden dann eine bitweise
 *     Konsens-Spur.
 *   - Konflikte (Weak Bits / Instabilität) werden NICHT geglättet, sondern
 *     als Weak-Mask/Statistik konserviert.
 */

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct flux_consensus_stats {
    uint32_t revs_in;
    uint32_t revs_used;
    uint32_t anchor_hits;
    uint32_t weak_bits;
    uint32_t unanimous_bits;
    uint32_t total_bits;
} flux_consensus_stats_t;

/* Find a stable MFM sync anchor (0x4489) in a raw MFM bitstream.
 *
 * raw_bits: MSB-first bitstream of clock+data pairs as generated by
 *           flux_mfm_decode_pll_raw().
 * raw_len_bits: length in bits.
 *
 * Returns 0 on success and writes anchor_bit (bit position of first 0x4489).
 * Returns -1 if no anchor was found.
 */
int flux_find_mfm_sync_anchor_4489(
    const uint8_t *raw_bits,
    size_t raw_len_bits,
    size_t *anchor_bit);

/* Circular rotate (bit shift) a bitstream by rot bits.
 *
 * rot is modulo in_len_bits.
 * out must have >= ceil(in_len_bits/8).
 */
int flux_rotate_bits(
    const uint8_t *in_bits,
    size_t in_len_bits,
    size_t rot,
    uint8_t *out_bits,
    size_t out_bytes_cap);

/* Build a multi-rev consensus track.
 *
 * Inputs are N revolutions already rotated to the same sync anchor.
 * Each revolution may differ in length. We use min length across revs.
 *
 * out_bits: consensus bits (raw MFM)
 * weak_mask: optional per-bit mask (1 = disputed). May be NULL.
 */
int flux_build_consensus_bits(
    const uint8_t * const *revs_bits,
    const size_t *revs_len_bits,
    uint32_t nrevs,
    uint8_t *out_bits,
    size_t out_bytes_cap,
    size_t *out_len_bits,
    uint8_t *weak_mask,
    size_t weak_bytes_cap,
    flux_consensus_stats_t *stats_out);

#ifdef __cplusplus
}
#endif
